# Generated by Django 3.1 on 2021-03-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('age', models.PositiveSmallIntegerField(blank=True, default=18, null=True, verbose_name='age')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.PositiveIntegerField(blank=True, null=True)),
                ('profession', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
