# Generated by Django 3.1 on 2021-04-21 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210404_1924'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='accounts_profile',
        ),
    ]
