# Generated by Django 3.1 on 2021-04-21 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210404_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.MaxLengthValidator, django.core.validators.RegexValidator('^[\\w\\.@+\\-\\s]+$', 'Enter a valid username. This value may contain only letters, numbers, spaces and @ . + - _ characters.')]),
        ),
    ]
