# Generated by Django 3.1.4 on 2021-03-21 11:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organizer',
            new_name='Task',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
