# Generated by Django 3.1 on 2021-04-04 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='memo',
            field=models.TextField(blank=True, validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator]),
        ),
    ]
