# Generated by Django 3.1 on 2021-04-06 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210404_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='reminder',
            new_name='remind_at',
        ),
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='task',
            name='memo',
            field=models.TextField(blank=True),
        ),
    ]
