# Generated by Django 3.1 on 2021-04-11 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20210406_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='important',
            new_name='is_important',
        ),
    ]
