# Generated by Django 3.1 on 2021-04-21 17:57

import django.core.validators
from django.db import migrations, models
import tasks.utils


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20210411_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.validate_image_file_extension, tasks.utils.validate_image_size]),
        ),
        migrations.AlterModelTable(
            name='task',
            table='tasks_task',
        ),
    ]
